### ISSUE TITLE
Installation breaks frontend (using RedisBackend)

### ISSUE THREAD

**Issue by tobenschmidt** [qbus-agentur/skip_page_is_being_generated#1]
Installation of version 1.1.2 in TYPO3 CMS 7.6.15 breaks the frontend. The error message is: 

> The specified lifetime "-1" must be greater or equal than zero.

**Comment by bnf** [comment]
Hm.. thats a bit of a problem, as this extension is build around the fact that lifetime -1 immediately [1] invalidates the temporary content.
Acutally it's only the RedisBackend that is affected [2], other cache Backends like Typo3DatabaseBackend allow lifetime to be -1. I'll update the title accordingly.

[1] https://github.com/qbus-agentur/skip_page_is_being_generated/blob/1.1.2/Classes/Hooks/SetPageCacheHook.php#L25
[2] https://github.com/TYPO3/TYPO3.CMS/blob/7.6.15/typo3/sysext/core/Classes/Cache/Backend/RedisBackend.php#L283

**Comment by bnf** [comment]
It's fixed for me with commit 172f2c6. I've released 1.1.3. Thanks for the report!

**Comment by tobenschmidt** [comment]
Thanks for the quick fix! Using the fixed extension for a week now without any problems.
